PRODUCTS = {
    "smartphones": {
        "title": "smartphones",
        "description": "Якийсь опис категорії товарів Смартфони",
        "products": [
            {
                "id": 1,
                "name": "Samsung Galaxy S24",
                "brand": "Samsung",
                "price": 35999,
                "stock": 12,
                "color": "Black",
                "image_url": "https://images.samsung.com/is/image/samsung/p6pim/levant/galaxy-s24-s24-plus/gallery/levant-galaxy-s24-s24-plus-thumb-530909310?$684_547_PNG$",
            },
            {
                "id": 2,
                "name": "iPhone 15",
                "brand": "Apple",
                "price": 44999,
                "stock": 8,
                "color": "Blue",
                "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-blue-select-2023?wid=940&hei=1112&fmt=png-alpha&.v=1693366905638",
            },
            {
                "id": 3,
                "name": "Xiaomi Redmi Note 13 Pro",
                "brand": "Xiaomi",
                "price": 14999,
                "stock": 20,
                "color": "White",
                "image_url": "https://i01.appmifile.com/webfile/globalimg/products/pc/redmi-note-13-pro/White.png",
            },
        ],
    },
    "leptops": {
        "title": "leptops",
        "description": "Якийсь опис категорії товарів Ноутбуки",
        "products": [
            {
                "id": 4,
                "name": "Lenovo IdeaPad 3",
                "brand": "Lenovo",
                "price": 18999,
                "stock": 15,
                "ram": "8 GB",
                "image_url": "https://www.lenovo.com/medias/lenovo-laptop-ideapad-3-14-hero.png?context=bWFzdGVyfHJvb3R8ODc3NzI0fGltYWdlL3BuZ3xoN2QvaDg2LzE0MDcxNjk3ODMwNzE0LnBuZ3xmY2NiZjZmN2UwYmRlODQ0ZTNlYmUwZDM5N2QxY2Q3YzM0ZTIyZDFiYjM0ZGNlYjAxOWIwYTljMWYwZDI1",
            },
            {
                "id": 5,
                "name": "ASUS TUF Gaming F15",
                "brand": "ASUS",
                "price": 32999,
                "stock": 5,
                "ram": "16 GB",
                "image_url": "https://dlcdnwebimgs.asus.com/gain/2e671fce-3e72-409d-9fac-bddacb0064e2/w2560/h1440/",
            },
            {
                "id": 6,
                "name": "Apple MacBook Air M2",
                "brand": "Apple",
                "price": 49999,
                "stock": 7,
                "ram": "8 GB",
                "image_url": "https://www.apple.com/v/macbook-air-m2/g/images/overview/hero_endframe__eeoz4vq85tq2_large_2x.jpg",
            },
        ],
    },
    "TVs": {
        "title": "TVs",
        "description": "Якийсь опис категорії товарів Телевізори",
        "products": [
            {
                "id": 7,
                "name": "Samsung QLED 55Q60",
                "brand": "Samsung",
                "price": 24999,
                "stock": 10,
                "size": "55 inch",
                "image_url": "https://images.samsung.com/is/image/samsung/p6pim/levant/q60c/gallery/levant-q60c-55-qa55q60cawxxu-505008512?$720_576_PNG$",
            },
            {
                "id": 8,
                "name": "LG OLED C2",
                "brand": "LG",
                "price": 39999,
                "stock": 4,
                "size": "55 inch",
                "image_url": "https://www.lg.com/us/images/tvs/md07542170/gallery/55-oled-c2-oled-tv-01.jpg",
            },
            {
                "id": 9,
                "name": "Xiaomi Mi TV P1",
                "brand": "Xiaomi",
                "price": 11999,
                "stock": 18,
                "size": "43 inch",
                "image_url": "https://i01.appmifile.com/webfile/globalimg/products/pc/mi-tv-p1/43.png",
            },
        ],
    },
    "headphones": {
        "title": "headphones",
        "description": "Якийсь опис категорії товарів Навушники",
        "products": [
            {
                "id": 10,
                "name": "Apple AirPods Pro 2",
                "brand": "Apple",
                "price": 10499,
                "stock": 10,
                "type": "TWS",
                "image_url": "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/airpods-pro-2nd-gen-select–202309?wid=940&hei=1112&fmt=png-alpha&.v=1693486656277",
            },
            {
                "id": 11,
                "name": "Sony WH-1000XM5",
                "brand": "Sony",
                "price": 16999,
                "stock": 6,
                "type": "Over-ear",
                "image_url": "https://www.sony.com/image/1dbe2f141b9ae8a4a8bbe16f6be7047b?fmt=pjpeg&bgcolor=FFFFFF&wid=2515&hei=1320",
            },
            {
                "id": 12,
                "name": "JBL Tune 710BT",
                "brand": "JBL",
                "price": 3499,
                "stock": 22,
                "type": "Over-ear",
                "image_url": "https://uk.jbl.com/dw/image/v2/AAQA_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw707b8d66/JBL_TUNE_710BT_Product_Image_Hero_Black.png",
            },
        ],
    },
    "technics": {
        "title": "technics",
        "description": "Якийсь опис категорії товарів Побутова техніка",
        "products": [
            {
                "id": 13,
                "name": "Bosch Series 4 (пральна машина)",
                "brand": "Bosch",
                "price": 18999,
                "stock": 9,
                "type": "Пральна машина",
                "image_url": "https://media3.bosch-home.com/Product_Shots/700x700/WAJ2800S-05__01.jpg",
            },
            {
                "id": 14,
                "name": "Philips Airfryer XXL",
                "brand": "Philips",
                "price": 6999,
                "stock": 13,
                "type": "Фритюрниця",
                "image_url": "https://www.philips.co.uk/c-dam/b2c/pdp/fryer/hd9650-47-product-image-01-4500x3000.jpg",
            },
            {
                "id": 15,
                "name": "Dyson V12 Slim",
                "brand": "Dyson",
                "price": 21999,
                "stock": 5,
                "type": "Пилосос",
                "image_url": "https://dyson.com.au/media/image/7e/ae/75/dyson-v12slim-product.png",
            },
        ],
    },
}
